version: 2
jobs:
  maven/test:
    docker:
    - image: circleci/openjdk:8u252-jdk
    steps:
    - checkout

    #- run:
    #    name: Install Dependencies
    #    command: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
    
    - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: circleci-jsql-injection-{{ checksum "pom.xml" }}
    
    - run: mvn dependency:go-offline # gets the project dependencies
    
    - save_cache: # saves the project dependencies
        paths:
          - ~/.m2
        key: circleci-jsql-injection-{{ checksum "pom.xml" }}    
    
    - setup_remote_docker
    
    - run:
        name: Install apt-get
        command: |
            env | sort
            sudo apt-get update -y 
            sudo apt-get upgrade -y 
            sudo apt-get install tightvncserver xfonts-base iptables-persistent iptables
            docker -H ${DOCKER_HOST} run hello-world
            docker -H ${DOCKER_HOST} ps
            docker -H ${DOCKER_HOST} images
            docker ps
            docker images
            mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
    
    - run:
        name: Run Docker
        command: |
            ./model/src/test/resources/docker/script/build.sh
            ./model/src/test/resources/docker/script/run.sh
            ./model/src/test/resources/docker/script/buff.sh
            ./model/src/test/resources/docker/script/verify.sh 
                   
    #- run:
    #    name: Run Tests
    #    command: ./model/src/test/resources/vnc/execute-on-vnc.sh mvn clean verify
    #        
    #- run:
    #    name: Run Tests
    #    command: ./model/src/test/resources/docker/script/verify.sh
    #
    #- save_cache:
    #    paths:
    #    - ~/.m2
    #    key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    #- store_test_results:
    #    path: target/surefire-reports
    
workflows:
  maven_test:
    jobs:
    - maven/test
  version: 2
  
general:
  branches:
    only:
     - circleci-master