version: 2
jobs:
  maven/test:
    docker:
    # - image: docker:17.05.0-ce-git
    - image: circleci/openjdk:8u252-jdk
    steps:
    - checkout
    #setup_remote_docker
    #- run:
    #    name: Generate Cache Checksum
    #    command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
    #- restore_cache:
    #    key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    #    
    #- run:
    #    name: Install Dependencies
    #    command: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
        
    - run:
        name: Install apt-get
        command: |
            #docker info
            # sudo: not found 
            # apt-get: not found 
            sudo apt-get update -y 
            sudo apt-get upgrade -y 
            sudo apt-get install tightvncserver xfonts-base iptables-persistent iptables
            # setup_remote_docker: command not found
            env | sort
            sudo iptables -L -n -t nat
            sudo iptables-save > /etc/iptables/rules.v4
            sudo systemctl restart docker.service
            # setup_remote_docker && setup-docker-engine
            sudo dockerd
            pwd
            sudo docker network create persistence_backend
            pwd
            docker ps
            pwd
            # sudo service start docker
            # sudo service docker status
            # sudo service docker start
            # sudo service docker status
            # sudo systemctl start docker
            # docker ps
            docker run hello-world
        
    - run:
        name: Run Docker
        command: |
            ./model/src/test/resources/docker/script/build.sh
            ./model/src/test/resources/docker/script/run.sh
            ./model/src/test/resources/docker/script/buff.sh
            ./model/src/test/resources/docker/script/verify.sh 
                   
    #- run:
    #    name: Run Tests
    #    command: ./model/src/test/resources/vnc/execute-on-vnc.sh mvn clean verify
    #        
    #- run:
    #    name: Run Tests
    #    command: ./model/src/test/resources/docker/script/verify.sh
    #
    #- save_cache:
    #    paths:
    #    - ~/.m2
    #    key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    #- store_test_results:
    #    path: target/surefire-reports
workflows:
  maven_test:
    jobs:
    - maven/test
  version: 2
  
general:
  branches:
    only:
     - circleci-master