version: 2
jobs:
  maven/test:
    docker:
    - image: circleci/openjdk:8u252-jdk
    steps:
    - checkout

    - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: circleci-jsql-injection-{{ checksum "pom.xml" }}
    
    - run: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
    
    - save_cache: # saves the project dependencies
        paths:
          - ~/.m2
        key: circleci-jsql-injection-{{ checksum "pom.xml" }}    
    
    - setup_remote_docker: 
        docker_layer_caching: true
    
    - run:
        name: Install apt-get
        command: |
            env | sort
            sudo apt-get update -y 
            sudo apt-get upgrade -y 
            sudo apt-get install tightvncserver xfonts-base iptables-persistent iptables
    
    - run:
        name: Run Docker
        command: |
            ./model/src/test/resources/docker/script/build.sh
            ./model/src/test/resources/docker/script/run.sh
            ./model/src/test/resources/docker/script/buff.sh
            ./model/src/test/resources/docker/script/verify.sh 

    - run:
        name: Run Tests
        command: ./model/src/test/resources/vnc/execute-on-vnc.sh mvn clean verify
            
    - run:
        name: Run Tests
        command: ./model/src/test/resources/docker/script/verify.sh
        
    - store_test_results:
        path: target/surefire-reports
    
workflows:
  maven_test:
    jobs:
    - maven/test
  version: 2
  
general:
  branches:
    only:
     - circleci-master