on:
  push:
    branches: [ master ]
    
env:
  MAVEN_NASHORN: ""
  MAVEN_BYTEBUDDY: ""
  DOCKER_RESOURCES: ./model/src/test/resources/docker

jobs:

  set-global-env-var:
    runs-on: ubuntu-latest
    steps:
      - id: set-vars
        env:
          DOCKER_RESOURCES: ${{ env.DOCKER_RESOURCES }}
        run: echo "DOCKER_RESOURCES=${DOCKER_RESOURCES}" >> $GITHUB_OUTPUT
    outputs:
      DOCKER_RESOURCES: ${{ steps.set-vars.outputs.DOCKER_RESOURCES }}

  build-jdk11:
    needs: set-global-env-var
    uses: ./.github/workflows/build-jdk11.yml
    with:
      DOCKER_RESOURCES: ${{ needs.set-global-env-var.outputs.DOCKER_RESOURCES }}

  build-additional:
    needs: set-global-env-var
    uses: ./.github/workflows/build-additional.yml
    with:
      DOCKER_RESOURCES: ${{ needs.set-global-env-var.outputs.DOCKER_RESOURCES }}

  build:
    needs: set-global-env-var
    uses: ./.github/workflows/build.yml
    with:
      DOCKER_RESOURCES: ${{ needs.set-global-env-var.outputs.DOCKER_RESOURCES }}
    secrets: inherit

  codeql:
    uses: ./.github/workflows/codeql.yml

  release:
    needs: [build-jdk11, build, build-additional, codeql, virustotal]
    uses: ./.github/workflows/release.yml
    secrets: inherit