name: Java CI with Maven and Docker

on:
  push:
    branches: [ master ]
    
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  MAVEN_NASHORN: ""

jobs:
  build:
    name: Start databases and build project image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - jdk: 3.8.1-jdk-11-slim
          nashorn: -Dnashorn.args=--no-deprecation-warning
        - jdk: 3.8.1-openjdk-15-slim
          nashorn: ""
    env:
      JSQL_DOCKERFILE: ${{ matrix.jdk }}
      MAVEN_NASHORN: ${{ matrix.nashorn }}
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        # Disable shallow clone to send Git blame to Sonar
        fetch-depth: 0
    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    
    - name: Set Maven dependencies cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
              
    - name: Install Maven dependencies
      run: |
        mvn clean install -DskipTests dependency:tree
        
    - name: Build and start databases
      run: |
        docker-compose -f ./model/src/test/resources/docker/docker-compose.yml build --parallel
        docker-compose -f ./model/src/test/resources/docker/docker-compose.yml up -d
        
        ./model/src/test/resources/docker/healthcheck/healthcheck.sh
        ./model/src/test/resources/docker/script/buff.sh
        ./model/src/test/resources/docker/script/verify.sh
        
    - name: Build project container
      run: |
        docker build -t jsql:latest --build-arg JSQL_DOCKERFILE -f model/src/test/resources/docker/Dockerfile.jsql .

    - name: Run Maven unit and integration tests
      run: |
        ./.github/workflows/scripts/run-on-docker.sh "mvn clean verify -P jsql sonar:sonar"

    - name: Display database stats
      run: |
        ./model/src/test/resources/docker/script/verify.sh

    - name: Codecov scan
      run: |
        ./.github/workflows/scripts/run-on-docker.sh "(bash <(curl -s https://codecov.io/bash) || true)"

    - name: Codacy scan
      run: |
        ./.github/workflows/scripts/run-on-docker.sh "(bash <(curl -Ls https://coverage.codacy.com/get.sh) || true)"

    - name: Sonar scan on View module
      run: |
        ./.github/workflows/scripts/run-on-docker.sh "(cd view/ ; mvn sonar:sonar)"

    - name: Sonar scan on Model module
      run: |
        ./.github/workflows/scripts/run-on-docker.sh "(cd model/ ; mvn sonar:sonar)"

  codeql:
    uses: ./.github/workflows/run-codeql.yml

  crda:
    uses: ./.github/workflows/run-codeready.yml
    secrets: inherit