name: Run on Docker

on:
  workflow_call:
    inputs:
      command:
        type: string

jobs:
  build:
    name: Run on Docker
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Disable shallow clone to send Git blame to Sonar
          fetch-depth: 0

      - name: Run unit and integration tests
        # Pass GITHUB_SHA to Docker container
        run: |
          pwd
          ls -l
          docker images
          docker ps
          docker run                                          \
            -t                                                \
            -v "$HOME/.m2":/root/.m2                          \
            -v "$HOME/.sonar/cache":/root/.sonar/cache        \
            --network docker_jsql-network                     \
            -e GITHUB_SHA                                     \
            -e SONAR_TOKEN                                    \
            -e CODACY_PROJECT_TOKEN                           \
            -e CODECOV_TOKEN                                  \
            -e MAVEN_NASHORN                                  \
            jsql:latest                                       \
            ./model/src/test/resources/vnc/execute-on-vnc.sh  \
            bash -c '${{ inputs.command }}'
          
          DOCKER_RUN="$?"
          echo docker run exit code: $DOCKER_RUN
          if [ "${DOCKER_RUN}" != "0" ]; then exit 1; fi
