on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          crda: latest

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: CRDA Scan
        id: crda_scan
        uses: redhat-actions/crda@v1
        with:
          snyk_token: ${{ secrets.SNYK_TOKEN }}

      - name: Print Report Link
        run: echo ${{ steps.crda_scan.outputs.report_link }}
